server:
  port: 8097
  servlet:
    context-path: /api
    encoding:
      force: true
  error:
    include-stacktrace: ON_PARAM

spring:
  application:
    name: scheduling-api
  datasource:
    url: jdbc:postgresql://172.23.0.2:5432/scheduleds
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_y8Kq1GetQ/.well-known/jwks.json

springdoc:
  swagger-ui:
    disable-swagger-default-url: false
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    enabled: true
swagger-servers-urls: http://localhost:${server.port}${server.servlet.context-path},http://127.0.0.1:${server.port}${server.servlet.context-path}

feign:
  client:
    config:
      order-api:
        service:
          url: http://localhost:8078/api/v1
      auth-api:
        service:
          url: http://localhost:8099/api

redis:
  address: 172.23.0.3:6379

logging:
  level:
    org:
      springframework:
        security: DEBUG